#!/usr/bin/bash
set -e

sourceUrl=$1

# Parse source URL

username=$(echo "${sourceUrl}" | awk -F '/' '{print $4}')
repoName=$(echo "${sourceUrl}" | awk -F '/' '{print $5}')

# Get latest tag

latestTag=$(curl --silent "https://api.github.com/repos/${username}/${repoName}/releases" | jq '.[0].tag_name' | sed -e 's/"//g' -e 's/v//')

if [ -z "${latestTag}" ]
then
	${BUILDTOPIA_UTILS} error "    > Distribution version returned is empty. An error has occurred."
	exit 1
else
	echo ${latestTag}
	exit 0
fi
