#!/usr/bin/bash
set -e

#
## CONFIGURATION VARIABLES
#

DEFAULT_VIEWER="bat"

#
## FUNCTIONS
#

verify_config_file() {
    if ! [ -f ${TARGET_DIR}/config.json ]
    then
        ${SYNCTROPY_UTILS} error "Config file not found at '${TARGET_DIR}/config.json'"
        exit 1
    fi
}

#
##
#

verify_config_file

${DEFAULT_VIEWER} ${TARGET_DIR}/config.json

exit $?
